// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxblonyudpusetmccvmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Ymxvbnl1ZHB1c2V0bWNjdm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODQ1MzIsImV4cCI6MjA1NTY2MDUzMn0.VrK_v6oOFEi8yX4eJiZ-7OomN9wvf7RrWWvxhuFxHTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);